package protocol;

public enum RequestType {
    // Auth
    LOGIN,
    LOGOUT,
    REGISTER,
    FORGOT_PASSWORD,
    VERIFY_OTP,
    RESET_PASSWORD,

    // TKB
    GET_SCHEDULE_BY_DAY,
    GET_SCHEDULE_BY_WEEK,
    GET_SCHEDULE_BY_SUBJECT,
    SYNC_SCHEDULE,

    // Diem danh
    OPEN_SESSION,
    CLOSE_SESSION,
    SUBMIT_ATTENDANCE,
    CHECKIN_GPS,
    CHECKIN_WIFI,
    GET_ATTENDANCE_HISTORY,
    GET_ATTENDANCE_STATS,

    // Xuat file
    EXPORT_CSV,
    EXPORT_EXCEL,

    // Chat
    SEND_CHAT,
    GET_CHAT_HISTORY,
    GET_CHAT_ROOMS,

    // Thong bao
    GET_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,

    // Lecturer data
    GET_LECTURER_CLASSES,
    GET_LECTURER_SCHEDULE,
    GET_LECTURER_ATTENDANCE_LIST,
    GET_LECTURER_EXPORT_DATA,
    GET_LECTURER_STATS,
    GET_LECTURER_DASHBOARD_STATS,
    GET_LECTURER_TODAY_SCHEDULE,
    GET_ACTIVE_SESSIONS,

    // Student data
    GET_ACTIVE_SESSION_FOR_STUDENT,
    GET_STUDENT_TODAY_SCHEDULE,
    GET_STUDENT_STATS,

    // AI tools
    AI_TOOL_QUERY,

    // System
    PING,
    ERROR
}
